# Book settings
title: "Our Handbook"
author: The Our Handbook Community
# logo: images/logo.png
url: "http://very-good-science.github.io/our-handbook"

#######################################################################################
# HTML settings

html:
    extra_navbar: |
        <div>
            Handbook created using <a href="https://github.com/very-good-science/our-meta-handbook">Our Handbook</a>.
            Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.
        </div>
    comments:
      hypothesis: true
      
#######################################################################################

sphinx:
    extra_extensions:
        - sphinx_inline_tabs
    extra_footer: |
        <p>
            License: <a href="https://creativecommons.org/licenses/by/3.0/legalcode">CC-BY 3.0</a>
        </p>
    config:
        html_show_copyright: false
